version: "3.0"
services:
  mq:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - target: 5672
        published: ${AMQP_PORT:-5672}
        protocol: tcp
        mode: host
      - target: 15672
        published: ${MANAGEMENT_UI_PORT:-15672}
        protocol: tcp
        mode: host
